website/buildings/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ImageCollectionView.as_view(), name='buildings'),
]

website/events/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.SectionView.as_view(), name='events'),
    path('calendar/', views.calendar, name='calendar'),
    path('upcoming/', views.EventView.as_view(), name='upcoming'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('archives/', include('archives.urls')),
    path('', include('frontpage.urls')),
    path('archives/buildings/', include('buildings.urls')),
    path('newsletters/', include('newsletters.urls')),
    path('events/', include('events.urls')),
]

website/buildings/models.py
from django.db import models


class ImageCollection(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Image(models.Model):
    name = models.CharField(max_length=30)
    caption = models.CharField(max_length=300)
    url = models.URLField(max_length=200)
    image_collection = models.ForeignKey(ImageCollection, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

website/buildings/views.py
from django.shortcuts import render
from django.views import generic

from .models import ImageCollection


class ImageCollectionView(generic.ListView):
    model = ImageCollection

website/buildings/templates/buildings/imagecollection_list.html
{% extends "frontpage/basic_template.html" %}

{% block content %}
<body class="bg-info">
    <div class="container-fluid pt-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'archives' %}">Archives</a></li>
            <li class="breadcrumb-item active" aria-current="page">Historic Buildings</li>
            </ol>
        </nav>
    </div>

    {% if imagecollection_list %}
    {% for collection in imagecollection_list %}
    <div class="container-fluid d-flex justify-content-center py-3">
        <div class="container card py-3">
            <h3 class="card-header text-center">{{ collection.name }}</h3>
            <div class="album">
                <!-- <div class="container py-5 mx-auto"> -->
                    <div class="row justify-content-center">
                        {% for image in collection.image_set.all %}
                        <div class="col-md-6 my-2">
                            <div class="card box-shadow h-100">
                                <img class="card-img-top" img src="{{ image.url }}" alt="Card image cap">
                                <div class="card-body">
                                    <p class="card-text text-center">{{ image.caption }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %} 
                    </div>
                <!-- </div> -->
            </div>
        </div>
    </div>
    {% endfor %}
    {% else %}
    <p>There are no newsletters to display.</p>
    {% endif %}
    </div>
    {% endblock %}
</body>